all:
	g++ MANTIS_Quadruple_MPI_RNG_verification.cpp Mantis.cpp --std=c++11 -Wall -O3 -o MANTIS_Quadruple_MPI_RNG_verification -l msmpi -L  "C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64" -I "C:\Program Files (x86)\Microsoft SDKs\MPI\Include"
clean:
	rm -f *.o MANTIS_Quadruple_MPI_RNG_verification
